apiVersion: v1
kind: Pod
metadata:
  name: kube-sched
  namespace: kube-system
spec:
  nodeName: dell03
  restartPolicy: Never
  containers:
  - name: kube-sched
    image: registry.cn-beijing.aliyuncs.com/doslab/kube-sched:v0.3.5-amd64
    command: ["kube-sched"]
    args: ["--masterUrl=", "--token="]